### ISSUE TITLE
Issues while deployin with gradle

### ISSUE THREAD

**Issue by anilgit90** [actions-on-google/dialogflow-updates-java#1]
Hi,

I encounter following issue when i run "gradle appengineDeploy",

> Task :compileJava FAILED
C:\Users\Anil\Documents\Programming\dialogflow-updates-java\src\main\java\com\ex
ample\NotificationsApp.java:146: error: incomparable types: boolean and <null>
    if (request.isPermissionGranted() != null && request.isPermissionGranted().b
ooleanValue()) {
                                      ^
C:\Users\Anil\Documents\Programming\dialogflow-updates-java\src\main\java\com\ex
ample\NotificationsApp.java:146: error: boolean cannot be dereferenced
    if (request.isPermissionGranted() != null && request.isPermissionGranted().b
ooleanValue()) {
                                                                              ^
C:\Users\Anil\Documents\Programming\dialogflow-updates-java\src\main\java\com\ex
ample\NotificationsApp.java:180: error: incomparable types: boolean and <null>
    if (request.isUpdateRegistered() != null && request.isUpdateRegistered().boo
leanValue()) {
                                     ^
C:\Users\Anil\Documents\Programming\dialogflow-updates-java\src\main\java\com\ex
ample\NotificationsApp.java:180: error: boolean cannot be dereferenced
    if (request.isUpdateRegistered() != null && request.isUpdateRegistered().boo
leanValue()) {
                                                                            ^
Note: C:\Users\Anil\Documents\Programming\dialogflow-updates-java\src\main\java\
com\example\ActionsServlet.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

What seems to be the issue?

**Comment by taycaldwell** [comment]
This issue has been addressed in https://github.com/actions-on-google/dialogflow-updates-java/commit/66777892eea558821bf0058b04336793a7d7dcc7.

Please re-run the sample with the applied changes, and open a new issue if you run into any further issues.

Thanks,
